spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: dev
  app-properties:
    userEndpoint: "https://your-api.com/"
    productEndpoint: "http://localhost:8887"
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: devuser
    password: devpassword
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  app-properties:
    userEndpoint: "https://your-api.com/"
    productEndpoint: "http://localhost:8887"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: testuser
    password: testpassword

---
spring:
  config:
    activate:
      on-profile: default
  app-properties:
    userEndpoint: "https://your-api.com/"
    productEndpoint: "http://localhost:8887"
  datasource:
    url: jdbc:h2:mem:defaultdb
    driver-class-name: org.h2.Driver
    username: defaultuser
    password: defaultpassword
server:
  port: 8085

